### ISSUE TITLE
RIMA-Backend api exception

### ISSUE THREAD

**Issue by ralf-berger** [ude-soco/RIMA#23]
The GloVe model might be required by RIMA-Backend api after all.

1. Register
2. Log in
3. Navigate to „Potential Interests“
4. Observe the following exception by RIMA-Backend api:

```
ERROR [django.request:228] log 24 140285114091328 Internal Server Error: /api/interests/getsimilarity/
Traceback (most recent call last):
  File "/home/app/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/app/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/app/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/app/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/app/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/app/.local/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/app/.local/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/app/.local/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/app/.local/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/app/interests/views.py", line 1006, in get
    return Response({"vals": getsimilarity()})
  File "/home/app/interests/topicutils.py", line 2519, in getsimilarity
    sim_scores = calculate_similarity(userinterest, tweetkeyword)
  File "/home/app/interests/Semantic_Similarity/Word_Embedding/IMsim.py", line 97, in calculate_similarity
    source_vec = glove_vectorize(source_doc)
  File "/home/app/interests/Semantic_Similarity/Word_Embedding/IMsim.py", line 51, in glove_vectorize
    vec = glove_model[word]
NameError: name 'glove_model' is not defined
```

**Comment by ralf-berger** [comment]
Fixed via e268a6f8, 73f23a7d, 98b32b8 etc.
