### ISSUE TITLE
NLTK download: Package '"stopwords' not found

### ISSUE THREAD

**Issue by ralf-berger** [ude-soco/RIMA#236]
```
/storage/glove/datatest_word2vec.txt already present
/storage/keyword_extractor/lda-1000-semeval2010.py3.pickle.gz already present
Downloading /storage/nltk now ...
<frozen runpy>:128: RuntimeWarning: 'nltk.downloader' found in sys.modules after import of package 'nltk', but prior to execution of 'nltk.downloader'; this may result in unpredictable behaviour
[nltk_data] Error loading "stopwords: Package '"stopwords' not found
[nltk_data]     in index
Error installing package. Retry? [n/y/e]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/app/.local/lib/python3.11/site-packages/nltk/downloader.py", line 2544, in <module>
    rv = downloader.download(
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.local/lib/python3.11/site-packages/nltk/downloader.py", line 788, in download
    choice = input().strip()
             ^^^^^^^
EOFError: EOF when reading a line
```

**Comment by ralf-berger** [comment]
Might be a temporary CDN issue, see: https://github.com/nltk/nltk/issues/3146

**Comment by ralf-berger** [comment]
Still not working.

```
Downloading /storage/nltk now ...
<frozen runpy>:128: RuntimeWarning: 'nltk.downloader' found in sys.modules after import of package 'nltk', but prior to execution of 'nltk.downloader'; this may result in unpredictable behaviour
[nltk_data] Error loading "stopwords: Package '"stopwords' not found
[nltk_data]     in index
Error installing package. Retry? [n/y/e]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/app/.local/lib/python3.11/site-packages/nltk/downloader.py", line 2544, in <module>
    rv = downloader.download(
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.local/lib/python3.11/site-packages/nltk/downloader.py", line 788, in download
    choice = input().strip()
             ^^^^^^^
EOFError: EOF when reading a line
```

**Comment by ralf-berger** [comment]
Workaround in 732cfe0
