### ISSUE TITLE
Fork "development": Worker warns about Nvidia issues on startup

### ISSUE THREAD

**Issue by ralf-berger** [ude-soco/RIMA#323]
```
Ensuring model data is present ...
Mirroring data from Model Server (http://sc-rima-model-server:8080) to /tmp/models ...
223 model files available
Migrating database ...
2023-07-23 21:25:15.601937: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2023-07-23 21:25:15.602166: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/home/app/.venv/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
2023-07-23 21:25:40,487 INFO [pytorch_pretrained_bert.modeling:230] modeling 11 139649421388672 Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2023-07-23 21:25:40,513 INFO [pytorch_transformers.modeling_bert:226] modeling_bert 11 139649421388672 Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2023-07-23 21:25:40,521 INFO [pytorch_transformers.modeling_xlnet:339] modeling_xlnet 11 139649421388672 Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2023-07-23 21:25:41,298 INFO [allennlp.common.registrable:73] registrable 11 139649421388672 instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2023-07-23 21:25:41,301 INFO [allennlp.common.registrable:73] registrable 11 139649421388672 instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2023-07-23 21:25:41,303 INFO [allennlp.common.registrable:73] registrable 11 139649421388672 instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2023-07-23 21:25:41,308 INFO [allennlp.common.registrable:73] registrable 11 139649421388672 instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2023-07-23 21:25:41,772 INFO [allennlp.commands.elmo:174] elmo 11 139649421388672 Initializing ELMo.
Traceback (most recent call last):
  File "manage.py", line 20, in <module>
    main()
  File "manage.py", line 16, in main
    execute_from_command_line(sys.argv)
  File "/home/app/.venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/app/.venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/app/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/app/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/home/app/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/app/.venv/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 65, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/home/app/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/app/.venv/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/app/.venv/lib/python3.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/app/.venv/lib/python3.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/app/.venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 398, in check
    for pattern in self.url_patterns:
  File "/home/app/.venv/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/app/.venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 579, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/app/.venv/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/app/.venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 572, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/app/interest_miner_api/urls.py", line 41, in <module>
    path('api/accounts/', include('accounts.urls')),
  File "/home/app/.venv/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/app/accounts/urls.py", line 3, in <module>
    from . import views
  File "/home/app/accounts/views.py", line 13, in <module>
    from interests.tasks import import_user_data
  File "/home/app/interests/tasks.py", line 9, in <module>
    from .utils import (
  File "/home/app/interests/utils.py", line 20, in <module>
    from interests.Keyword_Extractor.extractor import getKeyword
  File "/home/app/interests/Keyword_Extractor/__init__.py", line 4, in <module>
    from . import extractor
  File "/home/app/interests/Keyword_Extractor/extractor.py", line 13, in <module>
    from .Algorithms.embedding_based.data_model import SIF_RANK
  File "/home/app/interests/Keyword_Extractor/Algorithms/embedding_based/data_model.py", line 3, in <module>
    from .sifrank import SifRank
  File "/home/app/interests/Keyword_Extractor/Algorithms/embedding_based/sifrank/SifRank.py", line 2, in <module>
    from .utils import get_word_embedder
  File "/home/app/interests/Keyword_Extractor/Algorithms/embedding_based/sifrank/utils.py", line 3, in <module>
    from .embeddings.word_embeddings.flair_elmo_word_emb import FlairElmoWordEmbeddings
  File "/home/app/interests/Keyword_Extractor/Algorithms/embedding_based/sifrank/embeddings/word_embeddings/flair_elmo_word_emb.py", line 9, in <module>
    class FlairElmoWordEmbeddings(BaseWordEmbedder):
  File "/home/app/interests/Keyword_Extractor/Algorithms/embedding_based/sifrank/embeddings/word_embeddings/flair_elmo_word_emb.py", line 13, in FlairElmoWordEmbeddings
    weight_file=settings.ELMO_WEIGHT_FILE)):
  File "/home/app/.venv/lib/python3.7/site-packages/flair/embeddings/token.py", line 1840, in __init__
    options_file=options_file, weight_file=weight_file, cuda_device=cuda_device
  File "/home/app/.venv/lib/python3.7/site-packages/allennlp/commands/elmo.py", line 175, in __init__
    self.elmo_bilm = _ElmoBiLm(options_file, weight_file)
  File "/home/app/.venv/lib/python3.7/site-packages/allennlp/modules/elmo.py", line 526, in __init__
    self._token_embedder = _ElmoCharacterEncoder(options_file, weight_file, requires_grad=requires_grad)
  File "/home/app/.venv/lib/python3.7/site-packages/allennlp/modules/elmo.py", line 312, in __init__
    self._load_weights()
  File "/home/app/.venv/lib/python3.7/site-packages/allennlp/modules/elmo.py", line 400, in _load_weights
    self._load_char_embedding()
  File "/home/app/.venv/lib/python3.7/site-packages/allennlp/modules/elmo.py", line 406, in _load_char_embedding
    with h5py.File(cached_path(self._weight_file), 'r') as fin:
  File "/home/app/.venv/lib/python3.7/site-packages/allennlp/common/file_utils.py", line 106, in cached_path
    raise FileNotFoundError("file {} not found".format(url_or_filename))
FileNotFoundError: file /home/app/interests/Keyword_Extractor/Algorithms/embedding_based/auxiliary_data/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5 not found
```

**Comment by ralf-berger** [comment]
Regarding model file not being found, see #317
